### ISSUE TITLE
Failure on moving pipeline when stages had new runs

### ISSUE THREAD

**Issue by alivespirit** [ashwanthkumar/gocd-janitor#10]
Hi @ashwanthkumar, again me :)  
We are running janitor nightly and found an issue. Steps:  
1) First janitor execution moves pipeline artifacts to backup location (e.g. build #57, 2 runs of stages)
2) Stages of build are reran (this creates build #57, 3rd run)
3) Second janitor execution tries to move 3rd run of stages and fails with error

```
Exception in thread "main" java.lang.RuntimeException: org.apache.commons.io.FileExistsException: Destination '/var/lib/go-server/artifacts/backup_old_pipelines/FSS/57' already exists
```

Here's what we have in such case:

```
[root@ie1gos004 ~]# ll /var/lib/go-server/artifacts/backup_old_pipelines/FSS/57/deploy_group1/
total 8
drwxr-x--- 3 go go 4096 Jun  8 08:39 1
drwxr-x--- 3 go go 4096 Jun  8 08:47 2
[root@ie1gos004 ~]# ll /var/lib/go-server/artifacts/pipelines/FSS/57/deploy_group1/
total 4
drwxr-x--- 3 go go 4096 Jun 29 07:21 3
```

Would be best to fail only if directory with current run # of stage already exists in destination.

**Comment by ashwanthkumar** [comment]
@alivespirit Hello 😄 !
Good catch. In our setup, we don't use MoveAction at all 😛 . I've [fixed it](https://github.com/ashwanthkumar/gocd-janitor/commit/724f522f577bc1f084a62e76aff14fa9b1308087) now and made a release [v0.2.1-RC2](https://github.com/ashwanthkumar/gocd-janitor/releases/tag/v0.2.1-RC2). Please do give it a spin and let me know.

**Comment by alivespirit** [comment]
@ashwanthkumar Thanks a lot for a quick response! I've tested new version on our setup this night and it works quite fine :)
