### ISSUE TITLE
Index array seems off on White List

### ISSUE THREAD

**Issue by cholmes1111** [ashwanthkumar/gocd-janitor#3]
When I run Janitor against my pipelines, it appears to correctly determine if a pipeline failed or succeeded and the correct run number as shown in this screenshot:
![janitorstagecheck](https://cloud.githubusercontent.com/assets/14335463/12209684/0480409a-b612-11e5-9c8e-06f19f9bb467.png)

When it adds it to the whitelist however, it always has one number higher in the index. For example, my pipeline S3Plus1 has only ever run 2 times. The janitor logging shows adding it to the whitelist 3 times:

13:31:37.695 DEBUG in.ashwanthkumar.gocd.artifacts.Janitor - [WhiteList] - S3Plusl@3
13:31:37.695 DEBUG in.ashwanthkumar.gocd.artifacts.Janitor - [WhiteList] - S3Plusl@2
13:31:37.695 DEBUG in.ashwanthkumar.gocd.artifacts.Janitor - [WhiteList] - S3Plusl@1

The same thing happens with all the other pipelines as well. 

The problem with this is that if I've specified keep the 5 last good runs, one of the ones in the whitelist is a number to high and one of the runs that should be saved is going to be deleted.

**Comment by ashwanthkumar** [comment]
Adding 1 extra run to the whitelist for each pipeline is by design, but that shouldn't affect the number of runs to keep at all. 

Check out the codepath that does this - https://github.com/ashwanthkumar/gocd-janitor/blob/master/src/main/java/in/ashwanthkumar/gocd/artifacts/Janitor.java#L137-L138

**Comment by cholmes1111** [comment]
Ok. Thanks for clarifying for me. 

I hate to admit this, but the one programming language I still struggle greatly with is Java. If I'm understanding the section you pointed out correctly, it's going to always whitelist (keep) the most recent run and it's going to attempt to whitelist any currently running pipeline (+1). As long as those two are always added to the number specified in the .conf file, (in my case the .conf file specifies 5 runs to be kept, meaning the last 7 runs will be saved), that should be perfect. Sorry for my confusion.

**Comment by ashwanthkumar** [comment]
Yes, you're right. When designing this - I took a conscious call that when I ask for `N` versions - I want 'at least' last `N` versions and not exactly `N`.

**Comment by cholmes1111** [comment]
That's very good design in this use case. Thanks again!
