### ISSUE TITLE
Janitor configuration setting

### ISSUE THREAD

**Issue by cholmes1111** [ashwanthkumar/gocd-janitor#4]
I do not currently have a use case where one (or more) pipelines would be subject to an exception on the number of runs to keep. It's possible that some day in the future that may happen and I like the ability to override the default version to keep if I want to but the way it's currently setup you HAVE to specify a pipeline and the number of runs to keep. 
![janitoroptional](https://cloud.githubusercontent.com/assets/14335463/12209901/65896122-b613-11e5-8679-65dce02a7131.png)

Is there anyway to make the box I outlined in run an optional section of code? (When I commented it out and ran Janitor, it threw errors). I realize I can randomly pick one of my pipelines and set the number of runs to the default value (for example 5) but that seems overly burdensome.

**Comment by ashwanthkumar** [comment]
You should be able to specify an empty list, like 

```
pipelines = []
```

I still prefer to have an empty than not having them at all, because it makes it explicit that such a configuration key exist and being explicit is always a good thing.

**Comment by cholmes1111** [comment]
Thanks for the update ashwanthkumar. I like it explicitly stated too I just wanted the ability to not place a pipeline in there. I updated as you indicated and that did work. Thanks again.
