### ISSUE TITLE
Add prefix based pipelines support in the configuration

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-janitor#5]
@bharatak - Would you like to send [this change](https://github.com/Bahmni/gocd-janitor/commit/eccdd3ef7a09c212cfded90492aa569f99b8f582) upstream as a PR? I'm sure it would be super useful for others as well.

**Comment by bharatak** [comment]
I am very happy to contribute back. I am testing out something.. Will
definitely send you the pull request.

Regards,
Bharat

**Comment by ashwanthkumar** [comment]
:+1:

**Comment by ashwanthkumar** [comment]
Fixed via #6

**Comment by bharatak** [comment]
Awesome. Thanks a lot for the tool. It's pretty useful.

**Comment by ashwanthkumar** [comment]
^_^
